<?xml version="1.0" encoding="utf-8"?>
<!-- Created by cub: https://github.com/vivainio/leo-cub -->
<leo_file>
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
  <v t="cub.1786725356.346248974.1"><vh>@auto demo.cs</vh></v>
  <v t="cub.1786725356.346248974.2"><vh>@auto demo.js</vh></v>
  <v t="cub.1786725356.346248974.3"><vh>@auto demo.ts</vh></v>
  <v t="cub.1786725356.346248974.4"><vh>@auto demo.go</vh></v>
</vnodes>
<tnodes>
  <t tx="cub.1786725356.346248974.1"></t>
  <t tx="cub.1786725356.346248974.2"></t>
  <t tx="cub.1786725356.346248974.3"></t>
  <t tx="cub.1786725356.346248974.4"></t>
</tnodes>
</leo_file>
