use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::import::IdGenerator;
use crate::{Node, NodeId, Outline, Position, PositionId};

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Target {
    Position { position: PositionId },
    Node { node: NodeId },
}

/// One node of an `insert-tree`/`replace-tree`/`merge-tree` operation's input
/// tree: metadata under optional `_gnx`/`_body` keys, children keyed by their
/// own headline via `#[serde(flatten)]`. Mirrors the shape `json_tree`
/// produces for `inspect --format json-tree`, so a script can build one with
/// plain nested dicts. A missing `_body` means `""` for `insert-tree` and
/// `replace-tree`, but means "leave the existing body unchanged" for
/// `merge-tree`.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct TreeNode {
    #[serde(rename = "_gnx", skip_serializing_if = "Option::is_none")]
    pub gnx: Option<NodeId>,
    #[serde(rename = "_body", default, skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(flatten)]
    pub children: BTreeMap<String, TreeNode>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "op", rename_all = "kebab-case")]
pub enum Operation {
    Insert {
        parent: Option<NodeId>,
        index: Option<usize>,
        node: Node,
    },
    /// Insert a whole subtree (or several sibling subtrees) in one operation.
    /// Any node whose `_gnx` is omitted gets a fresh id from the batch's
    /// `gnx-prefix`. "parent" may be given instead as "parent-headline", a
    /// slash-separated headline path that is created (reusing any existing
    /// prefix) if it doesn't already exist.
    InsertTree {
        parent: Option<NodeId>,
        #[serde(rename = "parent-headline", default)]
        parent_headline: Option<String>,
        index: Option<usize>,
        tree: BTreeMap<String, TreeNode>,
    },
    /// Insert a new occurrence of an existing node. "parent" may be given
    /// instead as "parent-headline", the same as `insert-tree`.
    Clone {
        parent: Option<NodeId>,
        #[serde(rename = "parent-headline", default)]
        parent_headline: Option<String>,
        index: Option<usize>,
        node: NodeId,
    },
    SetHeadline {
        node: NodeId,
        headline: String,
        expected: Option<String>,
    },
    SetBody {
        node: NodeId,
        body: String,
        expected: Option<String>,
    },
    Remove {
        position: PositionId,
    },
    /// Remove a node's defining occurrence and its subtree, then insert a
    /// fresh `tree` in its place at the same parent/index. The target is a
    /// GNX or a slash-separated headline path (exactly one of the two). The
    /// removed node's GNX is discarded, not reused: like `insert-tree`, the
    /// new tree's nodes get a fresh id from `gnx-prefix` unless they set
    /// their own `_gnx`.
    ReplaceTree {
        node: Option<NodeId>,
        headline: Option<String>,
        tree: BTreeMap<String, TreeNode>,
    },
    /// Merge `tree` into an existing node's children, matching by headline.
    /// A headline already present is updated in place (its `_body`, if
    /// given, and its children merged recursively); a headline not present
    /// is inserted fresh, the same as `insert-tree`. Never removes a node.
    /// "parent" may be given instead as "parent-headline", the same as
    /// `insert-tree`.
    MergeTree {
        parent: Option<NodeId>,
        #[serde(rename = "parent-headline", default)]
        parent_headline: Option<String>,
        tree: BTreeMap<String, TreeNode>,
    },
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct OperationBatch {
    /// Prefix for GNXs generated by `insert-tree` nodes that omit `_gnx`.
    #[serde(rename = "gnx-prefix", default = "default_gnx_prefix")]
    pub gnx_prefix: String,
    pub operations: Vec<Operation>,
}

impl Default for OperationBatch {
    fn default() -> Self {
        Self {
            gnx_prefix: default_gnx_prefix(),
            operations: Vec::new(),
        }
    }
}

fn default_gnx_prefix() -> String {
    "cub".to_owned()
}

#[derive(Clone, Debug, Serialize)]
pub struct ApplyReport {
    pub applied: usize,
}

#[derive(Debug, Error)]
pub enum ApplyError {
    #[error("node already exists: {0}")]
    DuplicateNode(String),
    #[error("node not found: {0}")]
    NodeNotFound(String),
    #[error("position not found: {0}")]
    PositionNotFound(String),
    #[error("index {index} is out of range (length {len})")]
    BadIndex { index: usize, len: usize },
    #[error("precondition failed for {field} of node {node}")]
    Precondition { node: String, field: &'static str },
    #[error("batch would create an invalid outline: {0}")]
    Invalid(String),
}

impl Outline {
    /// Applies all operations to a copy and commits only if every operation succeeds.
    pub fn apply(&mut self, batch: &OperationBatch) -> Result<ApplyReport, ApplyError> {
        let mut next = self.clone();
        let mut ids = IdGenerator::with_prefix(
            batch.gnx_prefix.clone(),
            next.nodes.keys().cloned().collect(),
        );
        for op in &batch.operations {
            next.apply_one(op, &mut ids)?;
        }
        if let Some(error) = next.validate().first() {
            return Err(ApplyError::Invalid(error.to_string()));
        }
        *self = next;
        Ok(ApplyReport {
            applied: batch.operations.len(),
        })
    }

    fn apply_one(&mut self, op: &Operation, ids: &mut IdGenerator) -> Result<(), ApplyError> {
        match op {
            Operation::Insert {
                parent,
                index,
                node,
            } => {
                if self.nodes.contains_key(&node.id) {
                    return Err(ApplyError::DuplicateNode(node.id.0.clone()));
                }
                let id = node.id.clone();
                let children = children_for_parent(self, parent.as_ref())
                    .ok_or_else(|| ApplyError::NodeNotFound(parent.as_ref().unwrap().0.clone()))?;
                let at = index.unwrap_or(children.len());
                if at > children.len() {
                    return Err(ApplyError::BadIndex {
                        index: at,
                        len: children.len(),
                    });
                }
                children.insert(
                    at,
                    Position {
                        node: id.clone(),
                        children: vec![],
                    },
                );
                self.nodes.insert(id, node.clone());
            }
            Operation::InsertTree {
                parent,
                parent_headline,
                index,
                tree,
            } => {
                let parent = resolve_parent(self, parent, parent_headline, ids)?;
                let children = children_for_parent(self, parent.as_ref())
                    .ok_or_else(|| ApplyError::NodeNotFound(parent.as_ref().unwrap().0.clone()))?;
                let at = index.unwrap_or(children.len());
                if at > children.len() {
                    return Err(ApplyError::BadIndex {
                        index: at,
                        len: children.len(),
                    });
                }
                let positions = tree_to_positions(self, tree, ids)?;
                let children = children_for_parent(self, parent.as_ref()).unwrap();
                children.splice(at..at, positions);
            }
            Operation::Clone {
                parent,
                parent_headline,
                index,
                node,
            } => {
                if !self.nodes.contains_key(node) {
                    return Err(ApplyError::NodeNotFound(node.0.clone()));
                }
                // A clone's whole point is that every occurrence shares the
                // same subtree, so the new occurrence starts with a copy of
                // an existing occurrence's children rather than none --
                // otherwise it would diverge from the node it was just
                // cloned from the instant it was created.
                let cloned_children = children_ref(self, Some(node))
                    .map(<[Position]>::to_vec)
                    .unwrap_or_default();
                let parent = resolve_parent(self, parent, parent_headline, ids)?;
                let children = children_for_parent(self, parent.as_ref())
                    .ok_or_else(|| ApplyError::NodeNotFound(parent.as_ref().unwrap().0.clone()))?;
                let at = index.unwrap_or(children.len());
                if at > children.len() {
                    return Err(ApplyError::BadIndex {
                        index: at,
                        len: children.len(),
                    });
                }
                children.insert(
                    at,
                    Position {
                        node: node.clone(),
                        children: cloned_children,
                    },
                );
            }
            Operation::SetHeadline {
                node,
                headline,
                expected,
            } => set_text(self.nodes.get_mut(node), node, expected, headline, true)?,
            Operation::SetBody {
                node,
                body,
                expected,
            } => set_text(self.nodes.get_mut(node), node, expected, body, false)?,
            Operation::Remove { position } => {
                let mut path: Vec<usize> = position
                    .0
                    .split('/')
                    .map(str::parse)
                    .collect::<Result<_, _>>()
                    .map_err(|_| ApplyError::PositionNotFound(position.0.clone()))?;
                let index = path
                    .pop()
                    .ok_or_else(|| ApplyError::PositionNotFound(position.0.clone()))?;
                let parent = if path.is_empty() {
                    None
                } else {
                    Some(PositionId(
                        path.iter()
                            .map(usize::to_string)
                            .collect::<Vec<_>>()
                            .join("/"),
                    ))
                };
                let children = self
                    .children_mut(parent.as_ref())
                    .ok_or_else(|| ApplyError::PositionNotFound(position.0.clone()))?;
                if index >= children.len() {
                    return Err(ApplyError::PositionNotFound(position.0.clone()));
                }
                children.remove(index);
                let used: std::collections::HashSet<_> =
                    positions(&self.roots).map(|p| p.node.clone()).collect();
                self.nodes.retain(|id, _| used.contains(id));
            }
            Operation::ReplaceTree {
                node,
                headline,
                tree,
            } => {
                let target = match (node, headline) {
                    (Some(node), None) => node.clone(),
                    (None, Some(headline)) => self
                        .resolve_headline_path(headline)
                        .map_err(|error| ApplyError::Invalid(error.to_string()))?,
                    _ => {
                        return Err(ApplyError::Invalid(
                            "replace-tree requires exactly one of \"node\" or \"headline\""
                                .to_owned(),
                        ));
                    }
                };
                let (parent, index) = locate_position(self, &target)
                    .ok_or_else(|| ApplyError::NodeNotFound(target.0.clone()))?;

                let children = children_for_parent(self, parent.as_ref()).unwrap();
                children.remove(index);
                let used: std::collections::HashSet<_> =
                    positions(&self.roots).map(|p| p.node.clone()).collect();
                self.nodes.retain(|id, _| used.contains(id));

                let inserted = tree_to_positions(self, tree, ids)?;
                let children = children_for_parent(self, parent.as_ref()).unwrap();
                children.splice(index..index, inserted);
            }
            Operation::MergeTree {
                parent,
                parent_headline,
                tree,
            } => {
                let parent = resolve_parent(self, parent, parent_headline, ids)?;
                merge_tree(self, parent.as_ref(), tree, ids)?;
            }
        }
        Ok(())
    }
}

/// Resolve an operation's "parent"/"parent-headline" pair to a parent GNX
/// (`None` for the outline root). At most one of the two may be given;
/// "parent-headline" creates any missing segments of the path, reusing an
/// existing prefix, the same way `cub add` does.
fn resolve_parent(
    outline: &mut Outline,
    parent: &Option<NodeId>,
    parent_headline: &Option<String>,
    ids: &mut IdGenerator,
) -> Result<Option<NodeId>, ApplyError> {
    match (parent, parent_headline) {
        (Some(_), Some(_)) => Err(ApplyError::Invalid(
            "at most one of \"parent\" or \"parent-headline\" may be given".to_owned(),
        )),
        (Some(parent), None) => Ok(Some(parent.clone())),
        (None, Some(headline)) => outline
            .ensure_headline_path(headline, ids)
            .map(Some)
            .map_err(|error| ApplyError::Invalid(error.to_string())),
        (None, None) => Ok(None),
    }
}

/// Return the shared child list for a parent vnode. Leo writes the complete
/// subtree on the vnode's defining (first) occurrence; later clone occurrences
/// are references to that same structure.
fn children_for_parent<'a>(
    outline: &'a mut Outline,
    parent: Option<&NodeId>,
) -> Option<&'a mut Vec<Position>> {
    let Some(parent) = parent else {
        return Some(&mut outline.roots);
    };

    fn find<'a>(positions: &'a mut [Position], parent: &NodeId) -> Option<&'a mut Vec<Position>> {
        for position in positions {
            if &position.node == parent {
                return Some(&mut position.children);
            }
            if let Some(children) = find(&mut position.children, parent) {
                return Some(children);
            }
        }
        None
    }

    find(&mut outline.roots, parent)
}

/// Find `target`'s defining (first) occurrence and return its parent GNX
/// (`None` for a root) and index within that parent's children, in the
/// addressing `children_for_parent` expects.
fn locate_position(outline: &Outline, target: &NodeId) -> Option<(Option<NodeId>, usize)> {
    fn find(
        positions: &[Position],
        parent: Option<&NodeId>,
        target: &NodeId,
    ) -> Option<(Option<NodeId>, usize)> {
        for (index, position) in positions.iter().enumerate() {
            if &position.node == target {
                return Some((parent.cloned(), index));
            }
            if let Some(found) = find(&position.children, Some(&position.node), target) {
                return Some(found);
            }
        }
        None
    }

    find(&outline.roots, None, target)
}

/// Recursively materialize an `insert-tree` input tree into `outline.nodes`,
/// returning the new `Position`s to splice into a child list. Nodes with an
/// explicit `_gnx` that collides with an existing or already-inserted node
/// fail the whole operation.
fn tree_to_positions(
    outline: &mut Outline,
    tree: &BTreeMap<String, TreeNode>,
    ids: &mut IdGenerator,
) -> Result<Vec<Position>, ApplyError> {
    let mut positions = Vec::with_capacity(tree.len());
    for (headline, node) in tree {
        let id = match &node.gnx {
            Some(gnx) => {
                if outline.nodes.contains_key(gnx) {
                    return Err(ApplyError::DuplicateNode(gnx.0.clone()));
                }
                gnx.clone()
            }
            None => ids.next(),
        };
        let children = tree_to_positions(outline, &node.children, ids)?;
        outline.nodes.insert(
            id.clone(),
            Node {
                id: id.clone(),
                headline: headline.clone(),
                body: node.body.clone().unwrap_or_default(),
                vnode_attributes: Default::default(),
                tnode_attributes: Default::default(),
            },
        );
        positions.push(Position { node: id, children });
    }
    Ok(positions)
}

/// Return the shared child list for a parent vnode, read-only.
fn children_ref<'a>(outline: &'a Outline, parent: Option<&NodeId>) -> Option<&'a [Position]> {
    let Some(parent) = parent else {
        return Some(&outline.roots);
    };

    fn find<'a>(positions: &'a [Position], parent: &NodeId) -> Option<&'a [Position]> {
        for position in positions {
            if &position.node == parent {
                return Some(&position.children);
            }
            if let Some(children) = find(&position.children, parent) {
                return Some(children);
            }
        }
        None
    }

    find(&outline.roots, parent)
}

/// Find the one child of `parent` with the given `headline`. Errs if more
/// than one sibling shares it, since `merge-tree` has no other way to pick.
fn find_child_by_headline(
    outline: &Outline,
    parent: Option<&NodeId>,
    headline: &str,
) -> Result<Option<NodeId>, ApplyError> {
    let children = children_ref(outline, parent)
        .ok_or_else(|| ApplyError::NodeNotFound(parent.unwrap().0.clone()))?;
    let mut matches = children
        .iter()
        .filter(|position| outline.nodes[&position.node].headline == headline);
    let first = matches.next().map(|position| position.node.clone());
    if matches.next().is_some() {
        return Err(ApplyError::Invalid(format!(
            "merge-tree: headline {headline:?} is ambiguous under {}",
            parent.map_or("the outline root", |p| p.0.as_str())
        )));
    }
    Ok(first)
}

/// Merge `tree` into `parent`'s children, matching by headline. A headline
/// already present is updated in place (its body, if given, and its own
/// children merged recursively); a headline not present is inserted fresh.
/// Never removes an existing node.
fn merge_tree(
    outline: &mut Outline,
    parent: Option<&NodeId>,
    tree: &BTreeMap<String, TreeNode>,
    ids: &mut IdGenerator,
) -> Result<(), ApplyError> {
    for (headline, node) in tree {
        match find_child_by_headline(outline, parent, headline)? {
            Some(id) => {
                if let Some(body) = &node.body {
                    outline.nodes.get_mut(&id).unwrap().body = body.clone();
                }
                merge_tree(outline, Some(&id), &node.children, ids)?;
            }
            None => {
                let one = BTreeMap::from([(headline.clone(), node.clone())]);
                let inserted = tree_to_positions(outline, &one, ids)?;
                let children = children_for_parent(outline, parent)
                    .ok_or_else(|| ApplyError::NodeNotFound(parent.unwrap().0.clone()))?;
                children.extend(inserted);
            }
        }
    }
    Ok(())
}

fn set_text(
    node: Option<&mut Node>,
    id: &NodeId,
    expected: &Option<String>,
    value: &str,
    headline: bool,
) -> Result<(), ApplyError> {
    let node = node.ok_or_else(|| ApplyError::NodeNotFound(id.0.clone()))?;
    let current = if headline {
        &mut node.headline
    } else {
        &mut node.body
    };
    if expected.as_ref().is_some_and(|e| e != current) {
        return Err(ApplyError::Precondition {
            node: id.0.clone(),
            field: if headline { "headline" } else { "body" },
        });
    }
    *current = value.to_owned();
    Ok(())
}

fn positions(items: &[Position]) -> Box<dyn Iterator<Item = &Position> + '_> {
    Box::new(
        items
            .iter()
            .flat_map(|p| std::iter::once(p).chain(positions(&p.children))),
    )
}
